name: Publish to WinGet

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Create WinGet PR
        run: |
          $Parameters = @{
            Uri = "https://raw.githubusercontent.com/farag2/Sophia-Script-for-Windows/master/sophia_script_versions.json"
          }
          $Latest_Release = (Invoke-RestMethod @Parameters).Sophia_Script_Windows_11_PowerShell_5_1

          $Parameters = @{
            Uri     = "https://aka.ms/wingetcreate/latest"
            OutFile = "wingetcreate.exe"
          }
          Invoke-WebRequest @Parameters

          & .\wingetcreate.exe update TeamSophia.SophiaScript --urls "https://github.com/farag2/Sophia-Script-for-Windows/releases/download/$Latest_Release/Sophia.Script.for.Windows.11.v$($Latest_Release).zip" --version $Latest_Release --submit --token "${{ secrets.WINGET_TOKEN }}"
